version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: win/default
    steps:
    - checkout
    - run:
        name: Install MinGW
        command: choco install -y mingw
    - run:
        name: Add MinGW to PATH
        command: |
          $env:Path += ";C:\ProgramData\mingw64\mingw64\bin"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Machine)
    - run:
        command: go build; dir

workflows:
  main:
    jobs:
    - build