version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  test:
    executor:
      name: win/default
    steps:
    - checkout
    - run: "go version"
    - run: "g++ --version"

workflows:
  main:
    jobs:
    - test