version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: win/default
    steps:
    - run: go env
    - run: circleci-agent step halt
    - checkout
    - restore_cache:
        keys:
          - migw-key
    - run:
        name: Install MinGW
        command: |
          if (-not (Test-Path "C:\ProgramData\mingw64")) {
            choco install -y mingw
          }  
    - save_cache:
        paths:
          - C:\ProgramData\mingw64
        key: migw-key
    - run:
        name: Add MinGW to PATH
        command: |
          $env:Path += ";C:\ProgramData\mingw64\mingw64\bin"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Machine)
    - run:
        command: go build -ldflags '-H=windowsgui'
    - store_artifacts:
        path: ./aitts.exe

workflows:
  main:
    jobs:
    - build