version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: win/default
    steps:
    - checkout
    - run: "go version"
    - run:
         command: echo hello && echo $PATH
         shell: bash.exe
    - run:
          name: Install MinGW
          command: choco install -y mingw
    - run:
         command: g++ --version
         shell: bash.exe

workflows:
  main:
    jobs:
    - build