version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build-windows:
    executor:
      name: win/default
    environment:
      PIPER_WINDOWS_RELEASE: "https://github.com/rhasspy/piper/releases/download/2023.11.14-2/piper_windows_amd64.zip"
    steps:
    - checkout
    - restore_cache:
        keys:
          - migw-key
    - run:
        name: Install MinGW
        command: |
          if (-not (Test-Path "C:\ProgramData\mingw64")) {
            choco install -y mingw
          }  
    - save_cache:
        paths:
          - C:\ProgramData\mingw64
        key: migw-key
    - run:
        name: Add MinGW to PATH
        command: |
          $env:Path += ";C:\ProgramData\mingw64\mingw64\bin"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Machine)
    - restore_cache:
        keys:
          - go-pkg-{{ checksum "go.mod" }}
    - run:
        command: go build -ldflags '-H=windowsgui'
    - save_cache:
        key: go-pkg-{{ checksum "go.mod" }}
        paths:
          - C:\Users\circleci\go
    - run:
        name: Download Piper
        command: |
          Invoke-WebRequest $env:PIPER_WINDOWS_RELEASE -OutFile piper.zip
          Expand-Archive .\piper.zip -DestinationPath .
    - run:
        name: Prepare the package files
        command: |
          mkdir aitts
          mv aitts.exe aitts
          mv webui aitts
          mv piper aitts
          mv models aitts
    - run:
          name: Create a Zip file
          command: |
            cd aitts
            $ProgressPreference = "SilentlyContinue"
            Compress-Archive .\\ aitts.zip
    - store_artifacts:
        path: ./aitts/aitts.zip

  build-linux:
    machine:
      image: ubuntu-2204:2024.11.1
    environment:
      PIPER_LINUX_RELEASE: "https://github.com/rhasspy/piper/releases/download/2023.11.14-2/piper_linux_x86_64.tar.gz"
    steps:
    - checkout
    - run:
        name: Install go
        command: |
          sudo apt update
          sudo apt install -y golang-go
          go version
    - run:
        name: Install webkit2gtk-4
        command: |
          export DEBIAN_FRONTEND=noninteractive
          export NEEDRESTART_MODE=a
          sudo -E apt install -y libwebkit2gtk-4.1-dev
          sudo systemctl restart xvfb.service
    - run:
        name: Build binary
        command: |
          go build
    - run:
        name: Download Piper
        command: |
          wget $PIPER_LINUX_RELEASE -O piper.tar.gz
          tar -xvf piper.tar.gz
          ls -lh


workflows:
  main:
    jobs:
    # - build-windows
    - build-linux